# -*- coding: utf-8 -*-
"""relatorio.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19kEiijki1eIwMmYGzyGXMXtA1Lf4SPQ-

Desafio Gerar um relatorio que chegue todos os dias na caixa de entrada do email com o fechamento do IBOVESPA e Dólar!

# Passo 1 - Importar os módulos e bibliotecas.
# Passo 2 - Pegar dados do Ibovespa e do Dólar no Yahoo Finance

# Passo 3 - Manipular os dados para deixa-los nos formatos necessários

# Passo 4 - Calcular o retorno diário, mensal e anual.

# Passo 5 - Localizar, dentro das tabelas de retornos, os valores de fechamento de mercado que irão pro texto anexado no e-mail.

# Passo 6 - Fazer os gráficos de ativos

# Passo 7 - Enviar o e-mail.
"""

!pip install yfinance==0.1.74
!pip install mplcyberpunk
#!pip install pywin32

!pip install datetime

!pip install matplotlib

import pandas as pd
import datetime 
import yfinance as yf
#from matplotlib import pyploy as plt
import mplcyberpunk
#import win32com.client as win32

#from matplotlib import pyploy as plt

"""# Passo 2: Pegar dados no Yahoo Finance"""

nome_das_pessoas = ['Deixa o like', 'Curti video']
print(nome_das_pessoas[1])

codigos_de_negociacao = ['^BVSP', 'BRL=X']

hoje = datetime.datetime.now()
um_ano_atras = hoje - datetime.timedelta(days = 365)

dados_mercado = yf.download(codigos_de_negociacao, um_ano_atras, hoje )
display(dados_mercado)

"""# Passo 3.1 Manipulando os dados - seleção e exclusão de dados

"""

dados_fechamento = dados_mercado['Adj Close']
dados_fechamento.columns = [ 'dolar', 'ibovespa']

dados_fechamento = dados_fechamento.dropna()

dados_fechamento.head(50)
#dados_fechamento